### ISSUE TITLE
Error with creating/opening database file

### ISSUE THREAD

**Issue by Matteas-Eden** [SimonDaNinja/youtube_rss#9]
On **Arch Linux**, running commit 3166c53, I get the following error when trying to run `youtube_rss.py`:

```
Traceback (most recent call last):
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1281, in <module>
    database = doWaitScreen('', parseDatabaseFile, DATABASE_PATH)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 410, in doWaitScreen
    return curses.wrapper(doWaitScreenNcurses, message, waitFunction, *args, **kwargs)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 419, in doWaitScreenNcurses
    return waitFunction(*args, **kwargs)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 851, in parseDatabaseFile
    with open(filename, 'r') as filePointer:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matteas/.youtube_rss/database'
```
A quick workaround is to simply run `touch ~/.youtube_rss/database`, which allows the script to run, but doesn't ultimately solve the issue. When trying to do anything with subscriptions, there are then inevitably errors because the program is trying to read from an empty file. Such as:
```
Traceback (most recent call last):
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1284, in <module>
    doStartupMenu(runtimeConstants)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1151, in doStartupMenu
    doMethodMenu("Do you want to use tor?", menuOptions, showItemNumber=False)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1223, in doMethodMenu
    result = methodMenuDecision.executeDecision()
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 326, in executeDecision
    return self.function(*self.args, **self.kwargs)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1209, in doMainMenu
    doMethodMenu("What do you want to do?", menuOptions)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1223, in doMethodMenu
    result = methodMenuDecision.executeDecision()
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 326, in executeDecision
    return self.function(*self.args, **self.kwargs)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 981, in doInteractiveChannelSubscribe
    doMethodMenu(f"search results for '{query}', choose which " + \
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 1223, in doMethodMenu
    result = methodMenuDecision.executeDecision()
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 326, in executeDecision
    return self.function(*self.args, **self.kwargs)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 994, in doChannelSubscribe
    database = doWaitScreen('', parseDatabaseFile, DATABASE_PATH)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 410, in doWaitScreen
    return curses.wrapper(doWaitScreenNcurses, message, waitFunction, *args, **kwargs)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 419, in doWaitScreenNcurses
    return waitFunction(*args, **kwargs)
  File "/home/matteas/youtube_rss/./youtube_rss.py", line 852, in parseDatabaseFile
    return json.load(filePointer, cls = DatabaseDecoder)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I tried debugging it myself, but I don't know anything about `waitFunction` and the rest of the code makes it a little unclear exactly what the `database` file is supposed to look like. There's, uhh, no info in the README either, so I'm a little stuck. Figured I'd make an issue here instead of spending more time reverse engineering the code.

Any help is appreciated.

**Comment by SimonDaNinja** [comment]
Hi Matteas! Thanks for reporting this issue! I think I know what might cause this, but unfortunately I'll have to wait until my work ends today before I can fix it. I can imagine it's a bit convoluted to try to get into my codebase since there is no real design documentation at the moment.

This bug almost certainly arose around a week ago when I did a lot of refactoring of my code - I should add some tests of all basic behavior to avoid these sorts of issues arising in the future when I rework code (it's been on my mind for a while).

I think a workaround could be to fill the file database you created with the following content:

```
{
    "feeds": {}
    "id to title": {}
    "title to id": {}
}
```

**Comment by SimonDaNinja** [comment]
I think this commit should solve this issue: 68053bb3482b9c70fe00e64c5674623de625ab1c
If you pull, there should no longer be a problem
